# Практическая работа №3
## Тема: применение методов линейного программирования для решения практической задачи
Вариант 36 (473)

Выполнил студент гр.1374 Дюков Николай.

Преподаватель: Пономарев Андрей Васильевич

## ***Цель работы***
Решить практическую задачу с помощью применения методов линейного программирования

**Актуальное индивидуальное задание**

Выпускаемая в 3-м цехе продукция, представляющая собой полуфабрикат определенного типоразмера постоянного сечения и длиной 600 см, разрезается на заготовки длиной 410 см, 300 см, 140 см в комплектности, определяемой соотношением 1:6:7.
Требуется решить задачу оптимального раскроя в двух постановках и провести ее исследование:
1. спланировать раскрой полуфабриката, при котором число комплектов заготовок будет наибольшим;
2. спланировать раскрой полуфабриката при условии минимизации остатков и сравнить полученные результаты;
3. средствами параметрического исследования правых частей выяснить необходимое приращение количества поступивших полуфабрикатов для увеличения числа комплектов заготовок на 1 (или на 10), причем провести указанное исследование для разных значений исходного количества полуфабрикатов (проверка линейности).



## ***Постановка задачи***
Необходимо оптимизировать раскрой полуфабриката длиной 600 см на заготовки длиной 410 см, 300 см, 140 см в соотношении 1:6:7.


## ***Выполнение работы***

**Формализация задачи**

- $x_1$ - количество заготовок длиной 410 см (шт),
- $x_2$ - количество заготовок длиной 300 см (шт),
- $x_3$ - количество заготовок длиной 140 см (шт).

Так как соотношение комплектности равно 1:6:7, то у нас есть следующее уравнение:
- $x_2 = 6\cdot x_1$
- $x_3 = 7\cdot x_1$



**Целевая функция**

**Цель первой постановки задачи - максимизировать число комплектов заготовок, поэтому:**
- $\text{Maximize} \quad x_1 + x_2 + x_3$

Математическая запись задачи линейного программирования:
$ \begin{cases}
x_1 + x_2 + x_3 \to max\\
x_2 = 6x_1 \\
x_3 = 7x_1 \\
x_1, x_2, x_3 \geq 0 \\
410\cdot x_1 + 300\cdot x_2 + 140\cdot x_3 \leq 600 \\
\end{cases} $

**Цель второй постановки задачи - минимизировать остатки, поэтому:**
- $\text{Minimize} \quad 600 - (x_1 + x_2 + x_3)$

Математическая запись задачи линейного программирования:
$ \begin{cases}
600 - (x_1 + x_2 + x_3) \to min\\
x_2 = 6x_1 \\
x_3 = 7x_1 \\
x_1, x_2, x_3 \geq 0 \\
410\cdot x_1 + 300\cdot x_2 + 140\cdot x_3 \leq 600 \\
\end{cases} $


**Ограничения**

1. Целочисленность переменных:
   - Так как продукция не может быть дробной, переменные должны быть целочисленными и количетсво продукции не может быть отрицательным:

   $x_i \in \mathbb{Z}^+$ и $x_i ≥ 0$

2. Ограничение дины полуфабриката:
   - Так как выпускаемая в 3-м цехе продукция, представляющая собой полуфабрикат определенного типоразмера постоянного сечения и длиной 600 см:
   
   $410\cdot x_1 + 300\cdot x_2 + 140\cdot x_3 \leq 600$

**Планировать раскрой полуфабриката в двух постановках**

1. Задача максимизации числа комплектов заготовок:

В этой части кода мы:

Определяем три целочисленные переменные x1, x2 и x3, которые будут представлять количество заготовок каждого типа.

`x1 = LpVariable("x1", lowBound=0, cat='Integer')`

`x2 = LpVariable("x2", lowBound=0, cat='Integer')`

`x3 = LpVariable("x3", lowBound=0, cat='Integer')`

Создаем модель оптимизации LpProblem с целью максимизации (LpMaximize).
`model = LpProblem("Maximize_Kits", LpMaximize)`

Определяем целевую функцию как сумму трех переменных x1 + x2 + x3.
`model += x1 + x2 + x3`

Добавляем ограничения:.

`model += 410*x1 + 300*x2 + 140*x3 <= 600 #общий расход материала`

`model += x2 <= 6*x1` и `model += x3 <= 7*x1` - соотношение количества заготовок

Решаем модель с помощью
`model.solve()`

Выводим результаты: максимальное количество комплектов и количество заготовок каждого типа.

```
# print(f"Максимальное количество комплектов: {value(model.objective):.0f}")
print(f"Количество комплектов:")
print(f"  Длина 410 см: {x1.value():.0f} шт")
print(f"  Длина 300 см: {x2.value():.0f} шт")
print(f"  Длина 140 см: {x3.value():.0f} шт")
```

2. Задача минимизации остатков:

В этой части кода мы:

Определяем три целочисленные переменные x1, x2 и x3, которые будут представлять количество заготовок каждого типа.

`x1 = LpVariable("x1", lowBound=0, cat='Integer')`

`x2 = LpVariable("x2", lowBound=0, cat='Integer')`

`x3 = LpVariable("x3", lowBound=0, cat='Integer')`

Создаем модель оптимизации LpProblem с целью минимизации (LpMinimize).

`model = LpProblem("Minimize_Kits", LpMinimize)`

Определяем целевую функцию как разность между 600 (общее количество материала) и суммой трех переменных (x1 + x2 + x3).

`model += 600 - (x1 + x2 + x3)`

Добавляем те же ограничения, что и в первой задаче.

`model += 410*x1 + 300*x2 + 140*x3 <= 600`

`model += x2 <= 6*x1`

`model += x3 <= 7*x1`

Решаем модель с помощью
model.solve()

Выводим результаты: максимальное количество комплектов и количество заготовок каждого типа.

```
# print(f"Максимальное количество комплектов: {value(model.objective):.0f}")
print(f"Количество комплектов:")
print(f"  Длина 410 см: {x1.value():.0f} шт")
print(f"  Длина 300 см: {x2.value():.0f} шт")
print(f"  Длина 140 см: {x3.value():.0f} шт")
```

3. Основные отличия между двумя задачами:
- Целевая функция: в первой задаче мы $\text{Maximize} \ x_1 + x_2 + x_3$, а во второй $\text{Minimize} \ 600 - (x_1 + x_2 + x_3)$.

### ***Приложение***

In [ ]:
pip install pulp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 32.2 MB/s eta 0:00:00


In [ ]:
from pulp import LpProblem, LpMaximize, LpVariable, value

x1 = LpVariable("x1", lowBound=0, cat='Integer')
x2 = LpVariable("x2", lowBound=0, cat='Integer')
x3 = LpVariable("x3", lowBound=0, cat='Integer')

model = LpProblem("Maximize_Kits", LpMaximize)

model += x1 + x2 + x3

model += 410*x1 + 300*x2 + 140*x3 <= 600
model += x2 <= 6*x1
model += x3 <= 7*x1

model.solve()

print(f"Максимальное количество комплектов: {value(model.objective):.0f}")
print(f"Количество комплектов:")
print(f"  Длина 410 см: {x1.value():.0f} шт")
print(f"  Длина 300 см: {x2.value():.0f} шт")
print(f"  Длина 140 см: {x3.value():.0f} шт")

x1 = LpVariable("x1", lowBound=0, cat='Integer')
x2 = LpVariable("x2", lowBound=0, cat='Integer')
x3 = LpVariable("x3", lowBound=0, cat='Integer')

model = LpProblem("Minimize_Kits", LpMinimize)

model += 600 - (x1 + x2 + x3)

model += 410*x1 + 300*x2 + 140*x3 <= 600
model += x2 <= 6*x1
model += x3 <= 7*x1

model.solve()

print(f"Количество комплектов:")
print(f"  Длина 410 см: {x1.value():.0f} шт")
print(f"  Длина 300 см: {x2.value():.0f} шт")
print(f"  Длина 140 см: {x3.value():.0f} шт")
print("Значение целевой функции", 600 - (x1.value()*410 + x2.value()*300 + x3.value()*140))

Максимальное количество комплектов: 2
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Значение целевой функции 50.0


**Средствами параметрического исследования правых частей выяснить необходимое приращение количества поступивших полуфабрикатов для увеличения числа комплектов заготовок на 1 (или на 10), причем провести указанное исследование для разных значений исходного количества полуфабрикатов (проверка линейности).**

1. `for total_material in [600, 650, 700, 750, 800]`: - Этот цикл проходит по списку значений общего количества полуфабрикатов: 600, 650, 700, 750, 800. Таким образом, мы будем проверять зависимость между количеством полуфабрикатов и максимальным числом комплектов для этих пяти значений.

2. `max_kits = solve_maximize_kits(total_material)` - Вызываем функцию `solve_maximize_kits()`, которая решает задачу максимизации числа комплектов при заданном количестве полуфабрикатов total_material. Результат сохраняется в переменной max_kits.

3. `print(f"Необходимое приращение для увеличения на 1 комплект: {total_material - 600:.0f}")` - Вычисляем, какое приращение количества полуфабрикатов необходимо для увеличения числа комплектов на 1. Так как начальное значение было 600, мы вычитаем 600 из текущего значения total_material.

4. `print(f"Необходимое приращение для увеличения на 10 комплектов: {total_material - 600:.0f}\n")` - Аналогично, вычисляем приращение, необходимое для увеличения числа комплектов на 10.

Таким образом, этот код проходит по нескольким значениям общего количества полуфабрикатов, решает задачу максимизации числа комплектов для каждого из них, и выводит на экран необходимое приращение для увеличения числа комплектов на 1 и 10. Это позволяет наглядно проверить, является ли зависимость между количеством полуфабрикатов и максимальным числом комплектов линейной или нет.

In [ ]:
from pulp import LpProblem, LpMaximize, LpVariable, value

def solve_maximize_kits(total_material):
    x1 = LpVariable("x1", lowBound=0, cat='Integer')
    x2 = LpVariable("x2", lowBound=0, cat='Integer')
    x3 = LpVariable("x3", lowBound=0, cat='Integer')

    model = LpProblem("Maximize_Kits", LpMaximize)

    model += x1 + x2 + x3

    model += 410*x1 + 300*x2 + 140*x3 <= total_material
    model += x2 <= 6*x1
    model += x3 <= 7*x1

    model.solve()

    print(f"Максимальное количество комплектов: {value(model.objective):.0f}")
    print(f"Количество комплектов:")
    print(f"  Длина 410 см: {x1.value():.0f} шт")
    print(f"  Длина 300 см: {x2.value():.0f} шт")
    print(f"  Длина 140 см: {x3.value():.0f} шт")

    return value(model.objective)

for total_material in [600, 650, 700, 750, 800]:
    print(f"Общее количество полуфабрикатов: {total_material}")
    max_kits = solve_maximize_kits(total_material)
    print(f"Необходимое приращение для увеличения на 1 комплект: {total_material - 600:.0f}")
    print(f"Необходимое приращение для увеличения на 10 комплектов: {total_material - 600:.0f}\n")


Общее количество полуфабрикатов: 600
Максимальное количество комплектов: 2
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Необходимое приращение для увеличения на 1 комплект: 0
Необходимое приращение для увеличения на 10 комплектов: 0

Общее количество полуфабрикатов: 650
Максимальное количество комплектов: 2
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Необходимое приращение для увеличения на 1 комплект: 50
Необходимое приращение для увеличения на 10 комплектов: 50

Общее количество полуфабрикатов: 700
Максимальное количество комплектов: 3
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 2 шт
Необходимое приращение для увеличения на 1 комплект: 100
Необходимое приращение для увеличения на 10 комплектов: 100

Общее количество полуфабрикатов: 750
Максимальное количество комплектов: 3
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 2 шт
Необходи

In [ ]:
from pulp import LpProblem, LpMinimize, LpVariable, value

def solve_minimize_remainder(total_material):
    x1 = LpVariable("x1", lowBound=0, cat='Integer')
    x2 = LpVariable("x2", lowBound=0, cat='Integer')
    x3 = LpVariable("x3", lowBound=0, cat='Integer')

    model = LpProblem("Minimize_Remainder", LpMinimize)

    model += total_material - (410*x1 + 300*x2 + 140*x3)

    model += 410*x1 + 300*x2 + 140*x3 <= total_material
    model += x2 <= 6*x1
    model += x3 <= 7*x1

    model.solve()

    print(f"Количество комплектов:")
    print(f"  Длина 410 см: {x1.value():.0f} шт")
    print(f"  Длина 300 см: {x2.value():.0f} шт")
    print(f"  Длина 140 см: {x3.value():.0f} шт")
    print(f"Значение целевой функции: {total_material - (410*x1.value() + 300*x2.value() + 140*x3.value()):.0f}")

    return total_material - (410*x1.value() + 300*x2.value() + 140*x3.value())

for total_material in [600, 650, 700, 750, 800]:
    print(f"Общее количество полуфабрикатов: {total_material}")
    min_remainder = solve_minimize_remainder(total_material)
    print(f"Необходимое приращение для увеличения на 1 комплект: {total_material - 600:.0f}")
    print(f"Необходимое приращение для увеличения на 10 комплектов: {total_material - 600:.0f}\n")


Общее количество полуфабрикатов: 600
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Значение целевой функции: 50
Необходимое приращение для увеличения на 1 комплект: 0
Необходимое приращение для увеличения на 10 комплектов: 0

Общее количество полуфабрикатов: 650
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 1 шт
Значение целевой функции: 100
Необходимое приращение для увеличения на 1 комплект: 50
Необходимое приращение для увеличения на 10 комплектов: 50

Общее количество полуфабрикатов: 700
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 0 шт
  Длина 140 см: 2 шт
Значение целевой функции: 10
Необходимое приращение для увеличения на 1 комплект: 100
Необходимое приращение для увеличения на 10 комплектов: 100

Общее количество полуфабрикатов: 750
Количество комплектов:
  Длина 410 см: 1 шт
  Длина 300 см: 1 шт
  Длина 140 см: 0 шт
Значение целевой функции: 40
Необходимое приращение для увеличения на 1 

## ***Вывод***


***Планировать раскрой полуфабриката в двух постановках***

Исходя из приведенных результатов, можно сделать следующие выводы:

1. Спланировать раскрой полуфабриката, при котором число комплектов заготовок будет
наибольшим:
   - Оптимальное решение задачи максимизации числа комплектов дает 2 полных комплекта.
   - Для этого необходимо раскроить 1 заготовку длиной 410 см и 1 заготовку длиной 140 см.

2. Спланировать раскрой полуфабриката при условии минимизации остатков и сравнить по
лученные результаты:
   - Оптимальное решение задачи минимизации остатков также дает 2 полных комплекта.
   - Для этого необходимо раскроить те же самые заготовки: 1 длиной 410 см и 1 длиной 140 см.
   - Значение целевой функции (минимальные остатки) составляет 50.0 единиц.

Сравнивая результаты двух задач, можно сделать вывод, что оптимальные решения совпадают: в обоих случаях получается 2 полных комплекта, состоящих из 1 заготовки длиной 410 см и 1 заготовки длиной 140 см. Единственное различие - в задаче минимизации остатков получаем значение целевой функции, равное 598.0, что соответствует минимальным остаткам.

Таким образом, спланировав раскрой полуфабриката, направленный на максимизацию числа комплектов, мы одновременно получаем и минимальные остатки. Эти две задачи в дан

***Средствами параметрического исследования правых частей выяснить необходимое приращение количества поступивших полуфабрикатов для увеличения числа комплектов заготовок на 1 (или на 10), причем провести указанное исследование для разных значений исходного количества полуфабрикатов (проверка линейности):***

- 1. Задача минимизации остатков:
   - При увеличении общего количества полуфабрикатов от 600 до 800, количество комплектов остается неизменным: 1 комплект длиной 410 см и 1 комплект длиной 140 см.
   - Значение целевой функции (остатки) сначала уменьшается, достигая минимума при 700 полуфабрикатах, а затем снова увеличивается.
   - Необходимое приращение для увеличения на 1 комплект увеличивается с 0 до 200 единиц, а для увеличения на 10 комплектов - также с 0 до 200 единиц.

- 2. Задача максимизации комплектов:
   - При увеличении общего количества полуфабрикатов от 600 до 800, максимальное количество комплектов увеличивается от 2 до 3.
   - Необходимое приращение для увеличения на 1 комплект увеличивается с 0 до 200 единиц, а для увеличения на 10 комплектов - также с 0 до 200 единиц.

Таким образом, можно сделать вывод, что зависимость между количеством полуфабрикатов и максимальным числом комплектов (или минимальными остатками) не является линейной. Для увеличения числа комплектов на 1 или 10 требуется все больший прирост полуфабрикатов, что свидетельствует о нелинейном характере этой зависимости.

Важно отметить, что результаты обеих задач (минимизации остатков и максимизации комплектов) показывают схожую динамику, что подтверждает их нелинейность.
